mjaakko/NeoStumbler

app/src/main/java/xyz/malkki/neostumbler/scanner/quicksettings/ScannerTileService.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/AddQSTileDialog.kt, app/src/main/java/xyz/malkki/neostumbler/ui/screens/ReportsScreen.kt, app/src/main/res/values/strings.xml
=> Prompt user to add QS tile

app/src/main/java/xyz/malkki/neostumbler/ui/composables/MLSWarningDialog.kt, app/src/main/java/xyz/malkki/neostumbler/ui/screens/ReportsScreen.kt, app/src/main/java/xyz/malkki/neostumbler/utils/OneTimeActionHelper.kt, app/src/main/res/values/strings.xml
=> Add warning dialog about MLS shutting down

.github/workflows/build_release.yml
=> Build also fdroid variant when publishing a release

app/src/fdroid/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/full/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/main/java/xyz/malkki/neostumbler/constants/PreferenceKeys.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/MLSGeosubmit.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/ReportSendWorker.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/GeosubmitEndpointSettings.kt, app/src/main/res/values/strings.xml
=> Allow using custom endpoint for Geosubmit API

app/src/main/java/xyz/malkki/neostumbler/location/PlatformLocationSource.kt
=> Fix crash when starting scanning on older Android versions

app/src/main/java/xyz/malkki/neostumbler/StumblerApplication.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/ReportSendWorker.kt, app/src/main/res/drawable/sync_24.xml, app/src/main/res/values/strings.xml
=> Fix crash when uploading on older Android versions

app/build.gradle, app/src/main/java/xyz/malkki/neostumbler/StumblerApplication.kt, app/src/main/java/xyz/malkki/neostumbler/beacons/StubDistanceCalculator.kt
=> Use StubDistanceCalculator for beacon distances

app/src/main/java/xyz/malkki/neostumbler/extensions/geocoderExtensions.kt, app/src/main/java/xyz/malkki/neostumbler/utils/geocoder/PlatformGeocoder.kt, app/src/test/java/xyz/malkki/neostumbler/utils/geocoder/PlatformGeocoderTest.kt
=> Disable geocoding after 3 IOExceptions

app/src/main/java/xyz/malkki/neostumbler/ui/composables/rememberServiceConnection.kt
=> Fix scan button status not updating

app/src/main/java/xyz/malkki/neostumbler/constants/PreferenceKeys.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/GeosubmitParams.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/MLSGeosubmit.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/ReportSendWorker.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/GeosubmitEndpointSettings.kt, app/src/main/res/values/strings.xml
=> Allow setting full path to the Geosubmit API

app/src/full/AndroidManifest.xml, app/src/main/AndroidManifest.xml, app/src/main/java/xyz/malkki/neostumbler/MainActivity.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/quicksettings/ScannerTileService.kt, app/src/main/java/xyz/malkki/neostumbler/ui/screens/ReportsScreen.kt, app/src/main/res/values/strings.xml
=> Request background location permission from QS tile on Android 14+

.github/workflows/build.yml
=> Run build workflow for pull requests

app/src/full/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, fastlane/metadata/android/pt-BR/full_description.txt, fastlane/metadata/android/pt-BR/short_description.txt
This pull request provides PT-BR translations for the app, and the Fastlane component, separate commits.
This PR does not make any changes to anything dealing with building the app to use them! You'll have to do that manually. I'd do it but I don't know how to mess with that.
=> Translate into Brazilian Portuguese

app/src/main/res/values-pt-rBR/strings.xml
Didn't understand this string last time properly, thought it was how many reports were uploaded last upload, not the date the last upload was heh.
=> PT-BR: Fix wrong translation

app/src/main/java/xyz/malkki/neostumbler/db/entities/CellTower.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/Report.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/source/MultiSubscriptionCellInfoSource.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/source/TelephonyManagerCellInfoSource.kt
Fixes #90 
I don't have access to a 5G standalone network right now, so I can't test this
=> Collect data for 5G cell towers

app/src/main/java/xyz/malkki/neostumbler/geosubmit/GeosubmitParams.kt, app/src/test/java/xyz/malkki/neostumbler/geosubmit/GeosubmitParamsTest.kt
=> Remove consecutive slashes from the Geosubmit endpoint URL

app/src/main/java/xyz/malkki/neostumbler/ui/composables/ReportMap.kt
=> Use button with a background on the map for better contrast

app/src/main/java/xyz/malkki/neostumbler/ui/composables/ReportMap.kt
=> Track current location on the map

app/src/main/AndroidManifest.xml
open app instead of system app info page
before/after
https://github.com/user-attachments/assets/385a64ae-66b9-4b70-a683-7cba464e5e93
=> Open app on quick setting tile long-press

app/src/main/java/xyz/malkki/neostumbler/StumblerApplication.kt
=> Disable BeaconLibrary manifest checking 

app/src/fdroid/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/full/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/main/java/xyz/malkki/neostumbler/constants/PreferenceKeys.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/IgnoreScanThrottlingToggle.kt, app/src/main/res/values/strings.xml
=> Add support for ignoring Wi-Fi scan throttling

app/schemas/xyz.malkki.neostumbler.db.ReportDatabase/3.json, app/src/main/java/xyz/malkki/neostumbler/db/ReportDatabase.kt, app/src/main/java/xyz/malkki/neostumbler/db/dao/BluetoothBeaconDao.kt, app/src/main/java/xyz/malkki/neostumbler/db/dao/CellTowerDao.kt, app/src/main/java/xyz/malkki/neostumbler/db/dao/ExportDao.kt, app/src/main/java/xyz/malkki/neostumbler/db/dao/ReportDao.kt, app/src/main/java/xyz/malkki/neostumbler/db/dao/StatisticsDao.kt, app/src/main/java/xyz/malkki/neostumbler/db/dao/WifiAccessPointDao.kt, app/src/main/java/xyz/malkki/neostumbler/db/entities/BluetoothBeaconEntity.kt, app/src/main/java/xyz/malkki/neostumbler/db/entities/CellTowerEntity.kt, app/src/main/java/xyz/malkki/neostumbler/db/entities/ReportWithData.kt, app/src/main/java/xyz/malkki/neostumbler/db/entities/WifiAccessPointEntity.kt, app/src/main/java/xyz/malkki/neostumbler/db/migrations/RenameTablesToEntities.kt, app/src/main/java/xyz/malkki/neostumbler/domain/CellTower.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/Report.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/ReportSendWorker.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScanReportCreator.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/source/CellInfoSource.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/source/MultiSubscriptionCellInfoSource.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/source/TelephonyManagerCellInfoSource.kt
=> Fill cell tower data from other cells

app/build.gradle, app/src/main/java/xyz/malkki/neostumbler/db/dao/ReportDao.kt, app/src/main/java/xyz/malkki/neostumbler/db/entities/ReportWithStats.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/ConfirmationDialog.kt, app/src/main/java/xyz/malkki/neostumbler/ui/screens/ReportsScreen.kt, app/src/main/java/xyz/malkki/neostumbler/ui/viewmodel/ReportsViewModel.kt, app/src/main/res/values/strings.xml
=> Add ability to delete reports

app/src/main/java/xyz/malkki/neostumbler/ui/composables/ReportMap.kt, app/src/main/java/xyz/malkki/neostumbler/ui/viewmodel/MapViewModel.kt
* Change geohex resolution depending on the map zoom level
* Return to the previous map view when switching tabs
=> Map improvements

app/schemas/xyz.malkki.neostumbler.db.ReportDatabase/4.json, app/src/main/java/xyz/malkki/neostumbler/db/ReportDatabase.kt, app/src/main/java/xyz/malkki/neostumbler/db/entities/CellTowerEntity.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/Report.kt
=> Store MCC and MNC as strings in the database

app/schemas/xyz.malkki.neostumbler.db.ReportDatabase/5.json, app/src/main/java/xyz/malkki/neostumbler/db/ReportDatabase.kt, app/src/main/java/xyz/malkki/neostumbler/db/dao/ExportDao.kt, app/src/main/java/xyz/malkki/neostumbler/db/entities/CellTowerEntity.kt, app/src/main/java/xyz/malkki/neostumbler/domain/CellTower.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/Report.kt
=> Collect ARFCN from cell towers

app/src/full/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, fastlane/metadata/android/pt-BR/full_description.txt
=> PT-BR: refinement

app/src/main/res/values-de-rDE/strings.xml
=> Fix missing formatting arguments in the German translation

app/build.gradle, app/src/full/res/values-fr-rFR/strings.xml, app/src/main/res/values-fr-rFR/strings.xml, fastlane/metadata/android/fr-FR/full_description.txt, fastlane/metadata/android/fr-FR/short_description.txt, fastlane/metadata/android/fr-FR/title.txt
Note that I also have added a "glossary" into `strings.xml` using comment option. Feel free to remove it if not relevant or if it cause problems.
```
```
Also I have adopted this format, it's probably useful:
```diff
- <string name="ok">D'accord</string>
+ <string name="ok">D\'accord</string>
```
Thanks!
=>  Added French translation (fr-FR) 

app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/GeosubmitEndpointSettings.kt, app/src/main/res/drawable/warning_14sp.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values/strings.xml
=> Show a warning if an unencrypted endpoint is used

app/src/fdroid/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/full/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/main/java/xyz/malkki/neostumbler/constants/PreferenceKeys.kt, app/src/main/java/xyz/malkki/neostumbler/extensions/preferencesExtensions.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/MovementDetectorSettings.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/MultiChoiceSettings.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/ScannerNotificationStyleSettings.kt, app/src/main/java/xyz/malkki/neostumbler/utils/gpsStatusFlow.kt, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de-rDE/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr-rFR/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml
=> Show the number of satellites in use on the notification

app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/movement/SignificantMotionMovementDetector.kt
The idea of this is to also take the difference between locations into account, because the significant motion sensor doesn't seem to get triggered reliably e.g. when sitting in a car (even though it should: https://source.android.com/docs/core/interaction/sensors/sensor-types#significant_motion)
=> Improve significant motion movement detection

app/src/androidTest/java/xyz/malkki/neostumbler/utils/OneTimeActionHelperTest.kt, app/src/androidTest/java/xyz/malkki/neostumbler/utils/SuggestedServiceTest.kt, app/src/fdroid/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/full/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/Link.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/geosubmit/GeosubmitEndpointSettings.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/geosubmit/SuggestedServicesDialog.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/geosubmit/UnencryptedEndpointWarning.kt, app/src/main/java/xyz/malkki/neostumbler/utils/SuggestedService.kt, app/src/main/res/raw/suggested_services.json, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de-rDE/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr-rFR/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values/strings.xml
=> Add a list of suggested endpoints to the settings

.github/workflows/build.yml, .github/workflows/test.yml, app/build.gradle, app/src/androidTest/java/xyz/malkki/neostumbler/utils/OneTimeActionHelperTest.kt, app/src/test/java/xyz/malkki/neostumbler/extensions/FlowExtensionsTest.kt, app/src/test/java/xyz/malkki/neostumbler/scanner/WirelessScannerTest.kt
=> GitHub Actions improvements

app/build.gradle, app/src/fdroid/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/full/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/main/AndroidManifest.xml, app/src/main/java/xyz/malkki/neostumbler/MainActivity.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/LanguageSwitcher.kt, app/src/main/res/resources.properties, app/src/main/res/values-fi/strings.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/themes.xml
=> Add language switcher to the settings

app/src/main/AndroidManifest.xml, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/quicksettings/ScannerTileService.kt
Number of reports created is shown on the tile and the tile uses active mode
=> Improve Quick Settings tile

app/src/main/java/xyz/malkki/neostumbler/scanner/source/BeaconLibraryBluetoothBeaconSource.kt
=> Catch exception when starting to scan for Bluetooth beacon

app/src/full/kotlin/xyz/malkki/neostumbler/ui/composables/autoscan/AutoScanToggle.kt, app/src/main/java/xyz/malkki/neostumbler/extensions/contextExtensions.kt, app/src/main/java/xyz/malkki/neostumbler/geosubmit/ReportSendWorker.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/BatteryOptimizationsDialog.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/ManageStorage.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/ReportReuploadButton.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/ReportUploadButton.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/export/ExportCsvButton.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/export/ExportDatabaseButton.kt, app/src/main/java/xyz/malkki/neostumbler/ui/screens/ReportsScreen.kt
=> Report sending improvements

app/src/main/java/xyz/malkki/neostumbler/geosubmit/MLSGeosubmit.kt, app/src/test/java/xyz/malkki/neostumbler/geosubmit/MLSGeosubmitTest.kt
=> Fix Ichnaea compatibility by not encoding null values

app/build.gradle
=> Enable Dutch translation

app/build.gradle
=> Enable Ukrainian translation

app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/geosubmit/SuggestedServicesDialog.kt
=> Fix crash when opening links from suggested services dialog

app/src/main/java/xyz/malkki/neostumbler/ui/viewmodel/StatisticsViewModel.kt
=> Add data for missing days to avoid interpolating on the chart

app/build.gradle, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/LanguageSwitcher.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/MultiChoiceSettings.kt
Also enabled Russian translation
=> Set max height for language switcher

app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/IgnoreScanThrottlingToggle.kt, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de-rDE/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr-rFR/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/xyz/malkki/neostumbler/utils/RateLimiterTest.kt
=> Add description for Wi-Fi scan throttling setting

app/build.gradle, app/src/main/java/xyz/malkki/neostumbler/extensions/contextExtensions.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/quicksettings/ScannerTileService.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/ManageStorage.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/ReportReuploadButton.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/ReportUploadButton.kt, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de-rDE/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr-rFR/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values/strings.xml
=> Add support for plural strings

app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/SliderSetting.kt
=> Reset slider value to default when closing the dialog without saving

app/src/full/kotlin/xyz/malkki/neostumbler/ui/screens/settings/SettingsScreen.kt, app/src/full/res/values-ar/strings.xml, app/src/full/res/values-cs/strings.xml, app/src/full/res/values-de-rDE/strings.xml, app/src/full/res/values-fi/strings.xml, app/src/full/res/values-fr-rFR/strings.xml, app/src/full/res/values-hu/strings.xml, app/src/full/res/values-it/strings.xml, app/src/full/res/values-lt/strings.xml, app/src/full/res/values-nb-rNO/strings.xml, app/src/full/res/values-nl/strings.xml, app/src/full/res/values-pl/strings.xml, app/src/full/res/values-pt-rBR/strings.xml, app/src/full/res/values-pt/strings.xml, app/src/full/res/values-ru/strings.xml, app/src/full/res/values-uk/strings.xml, app/src/full/res/values-zh-rCN/strings.xml, app/src/full/res/values/strings.xml
=> Add description for fused location provider setting

app/src/androidTest/java/xyz/malkki/neostumbler/ui/composables/shared/DateRangePickerDialogTest.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/CoverageLayerSettings.kt
=> Do not save coverage layer settings when leaving the dialog + fix test

app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/LanguageSwitcher.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/MultiChoiceSettings.kt, app/src/main/res/values-fi/strings.xml, app/src/main/res/values/strings.xml
=> Add 'system default' to language switcher

app/src/full/kotlin/xyz/malkki/neostumbler/location/FusedLocationSource.kt, app/src/main/java/xyz/malkki/neostumbler/location/LocationSource.kt, app/src/main/java/xyz/malkki/neostumbler/location/PlatformLocationSource.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/movement/SignificantMotionMovementDetector.kt, app/src/main/java/xyz/malkki/neostumbler/ui/viewmodel/MapViewModel.kt
=> Use passive location provider with the motion sensor

app/build.gradle, app/src/full/res/values-ja/strings.xml, app/src/main/res/values-ja/strings.xml
=> Add Japanese

app/build.gradle, app/src/androidTest/java/xyz/malkki/neostumbler/ui/composables/shared/AreaPickerTest.kt, app/src/main/java/xyz/malkki/neostumbler/location/LocationSource.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/shared/AreaPicker.kt, app/src/main/java/xyz/malkki/neostumbler/ui/viewmodel/MapViewModel.kt
=> Check location permission before requesting location

app/src/main/java/xyz/malkki/neostumbler/ui/composables/managestorage/ManageStorage.kt, app/src/main/res/values-fi/strings.xml, app/src/main/res/values/strings.xml
=> Show database schema version in storage management dialog

app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/AutoUploadToggle.kt, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de-rDE/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-fr-rFR/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-nl/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-ta/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml, app/src/main/res/values/strings.xml
=> Add option to select the required network type for automatic uploads

app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/IgnoreScanThrottlingToggle.kt
=> Update Wi-Fi scan throttling toggle when scan throttling changed from system settings

app/src/androidTest/java/xyz/malkki/neostumbler/ui/composables/settings/privacy/WifiFilterSettingsTest.kt, app/src/androidTest/java/xyz/malkki/neostumbler/ui/composables/shared/DateRangePickerDialogTest.kt, app/src/main/java/xyz/malkki/neostumbler/constants/PreferenceKeys.kt, app/src/main/java/xyz/malkki/neostumbler/db/dao/ReportDao.kt, app/src/main/java/xyz/malkki/neostumbler/domain/WifiAccessPoint.kt, app/src/main/java/xyz/malkki/neostumbler/extensions/doubleExtensions.kt, app/src/main/java/xyz/malkki/neostumbler/ichnaea/ReportSendWorker.kt, app/src/main/java/xyz/malkki/neostumbler/ichnaea/ReportSender.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/ScannerService.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/WirelessScanner.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/data/ReportData.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/postprocess/HiddenWifiFilterer.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/postprocess/ReportPostProcessor.kt, app/src/main/java/xyz/malkki/neostumbler/scanner/postprocess/SsidBasedWifiFilterer.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/ToggleWithAction.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/SettingsGroup.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/privacy/WifiFilterSettings.kt, app/src/main/java/xyz/malkki/neostumbler/ui/screens/SettingsScreen.kt, app/src/main/res/values-fi/strings.xml, app/src/main/res/values/strings.xml, app/src/test/java/xyz/malkki/neostumbler/ichnaea/ReportSenderTest.kt, app/src/test/java/xyz/malkki/neostumbler/scanner/WirelessScannerTest.kt, app/src/test/java/xyz/malkki/neostumbler/scanner/postprocess/HiddenWifiFiltererTest.kt, app/src/test/java/xyz/malkki/neostumbler/scanner/postprocess/SsidBasedWifiFiltererTest.kt
=> Privacy options

app/src/main/java/xyz/malkki/neostumbler/db/dao/ReportDao.kt
=> Fetch reports with two queries to avoid problems with Room

app/src/main/res/values-pt-rBR/strings.xml
went to check if everything was spelt correctly (which Weblate doesn't really do and you have to depend on the browser spell check) and did find one occurrence, which made me replace 'excluir' with 'apagar'
=> translation: pt-BR: update translation

app/src/full/kotlin/xyz/malkki/neostumbler/ui/composables/settings/AutoScanToggle.kt, app/src/full/res/values-ar/strings.xml, app/src/full/res/values-cs/strings.xml, app/src/full/res/values-de-rDE/strings.xml, app/src/full/res/values-es/strings.xml, app/src/full/res/values-fi/strings.xml, app/src/full/res/values-fr-rFR/strings.xml, app/src/full/res/values-hu/strings.xml, app/src/full/res/values-it/strings.xml, app/src/full/res/values-iw/strings.xml, app/src/full/res/values-ja/strings.xml, app/src/full/res/values-lt/strings.xml, app/src/full/res/values-nb-rNO/strings.xml, app/src/full/res/values-nl/strings.xml, app/src/full/res/values-pl/strings.xml, app/src/full/res/values-pt-rBR/strings.xml, app/src/full/res/values-pt/strings.xml, app/src/full/res/values-ru/strings.xml, app/src/full/res/values-uk/strings.xml, app/src/full/res/values-zh-rCN/strings.xml, app/src/full/res/values-zh-rTW/strings.xml, app/src/full/res/values/strings.xml
=> Show error dialog when Google Play services is not available for autoscan

app/src/main/res/values-pl/strings.xml
=> Add missing 'other' plural for Polish

app/src/androidTest/java/xyz/malkki/neostumbler/ui/composables/shared/SliderSettingTest.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/SliderSetting.kt
=> Fix slider settings getting unexpected values 

app/build.gradle, app/lint.xml
includes #697 (but doesn't have to, I just kind of did it for continuity in case any of the files needing updates were german or french :P)
=> build: use a lint.xml with more restrictive translation checking

app/src/main/java/xyz/malkki/neostumbler/ichnaea/ReportSender.kt
=> Send max 999 reports per batch

app/src/main/java/xyz/malkki/neostumbler/constants/PreferenceKeys.kt, app/src/main/java/xyz/malkki/neostumbler/domain/LatLng.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/map/MapSettings.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/reports/details/ReportMap.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/settings/ParamField.kt, app/src/main/java/xyz/malkki/neostumbler/ui/composables/shared/AreaPicker.kt, app/src/main/java/xyz/malkki/neostumbler/ui/map/MapTileSource.kt, app/src/main/java/xyz/malkki/neostumbler/ui/map/updateMapStyleIfNeeded.kt, app/src/main/java/xyz/malkki/neostumbler/ui/screens/MapScreen.kt, app/src/main/java/xyz/malkki/neostumbler/ui/viewmodel/MapViewModel.kt, app/src/main/res/values-fi/strings.xml, app/src/main/res/values/strings.xml
=> Toggle for map coverage layer + show distance to the estimated location

app/src/full/res/values-fi/strings.xml, app/src/full/res/values/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values/strings.xml
=> Clarify background location permission rationales

.editorconfig, docs/user_guide.md
=> Add note about the language switcher to the user guide

app/src/main/java/xyz/malkki/neostumbler/ui/map/LifecycleAwareMapView.kt
=> Use simplified Chinese script on the map if there's no country or script specified
